# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

trigger:
  - main

pr:
  branches:
    include:
      - main

stages:
- stage: Docker 
  jobs:
  - job: orkestra
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: AzureOrkestraDockerHubConnection
    - task: Docker@2
      displayName: Build
      inputs:
        command: build
        repository: azureorkestra/orkestra
        tags: |
          $(Build.BuildNumber)
          latest
      condition: succeeded()
    - task: Docker@2
      displayName: Push 
      inputs:
        command: push
        repository: azureorkestra/orkestra
        tags: |
          $(Build.BuildNumber)
          latest
      condition: and(succeeded(),eq(variables.isMain, true))

- stage: Release 
  jobs:
  - job: orkestra
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: GitHubRelease@0
      displayName: 'Create GitHub Release'      
      inputs:
        tagPattern: v*
        gitHubConnection: GithubAzureOrkestra 
        repositoryName: Azure/Orkestra
        assets: $(Build.ArtifactStagingDirectory)/README.md
        isDraft: true
      condition: and(succeeded(),eq(variables.isMain, true))
      