apiVersion: orkestra.azure.microsoft.com/v1alpha1
kind: ApplicationGroup
metadata:
  name: bookinfo-with-keptn
spec:
  applications:
    - name: istio-base
      dependencies: []
      spec:
        chart:
          url: "https://istio-release.storage.googleapis.com/charts"
          name: base
          version: 1.12.0-alpha.1
        release:
          targetNamespace: istio-system
    - name: prometheus
      dependencies: []
      spec:
        chart:
          url: "https://nitishm.github.io/charts"
          name: prometheus
          version: 14.8.0
        release:
          targetNamespace: istio-system
    - name: istiod
      dependencies: [istio-base, prometheus]
      # dependencies: [istio-base]
      spec:
        chart:
          url: "https://istio-release.storage.googleapis.com/charts"
          name: istiod
          version: 1.12.0-alpha.1
        release:
          targetNamespace: istio-system
          timeout: 10m
          values:
            service:
              type: ClusterIP
    - name: istio-ingressgateway
      dependencies: [istiod]
      spec:
        chart:
          url: "https://istio-release.storage.googleapis.com/charts"
          name: gateway
          version: 1.12.0-alpha.1
        release:
          targetNamespace: istio-system
          timeout: 10m
    - name: bookinfo
      dependencies: [istio-ingressgateway]
      spec:
        chart:
          url: "https://nitishm.github.io/charts"
          name: bookinfo
          version: v3
        release:
          targetNamespace: bookinfo
          timeout: 10m
          values:
            istio:
              enabled: true
              fault:
                enabled: false
            ambassador:
              enabled: false
        workflow:
          - name: helmrelease
            dependencies: []
            type: helmrelease
            params: nil
          - name: keptn
            dependencies: ["helmrelease"]
            type: keptn
            params:
              configmapRef:
                name: keptn-bookinfo-config
                namespace: orkestra
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keptn-bookinfo-config
  namespace: orkestra 
data:
  config.yaml: |
    apiVersion: v2
    actions:
      - name: "Run hey"
        events:
          - name: "sh.keptn.event.test.triggered"
        tasks:
          - name: "Run hey load tests"
            image: "azureorkestra/hey"
            cmd: ["hey"]
            args: ["-host", "example.com", "-z", "5m", "http://gateway.istio-system.svc.cluster.local/productpage"]
            maxPollDuration: 10000
  keptn-config.json: |-
    {
      "url": "http://api-gateway-nginx.orkestra.svc.cluster.local/api",
      "namespace": "orkestra",
      "timeframe": "5m",
      "token": {
        "secretRef":  {
          "name": "keptn-api-token",
          "namespace": "orkestra"
        }
      }
    }
  shipyard.yaml: |-
    apiVersion: "spec.keptn.sh/0.2.2"
    kind: "Shipyard"
    metadata:
      name: "shipyard-bookinfo"
    spec:
      stages:
        - name: "dev"
          sequences:
            - name: "evaluation"
              tasks:
              - name: "test"
                properties:
                  teststrategy: "functional"
              - name: "evaluation"
  sli.yaml: |
    spec_version: "1.0"
    indicators:
      error_percentage: sum(rate(istio_requests_total{app="gateway", response_code="500"}[$DURATION_SECONDS])) / sum(rate(istio_requests_total{app="gateway"}[$DURATION_SECONDS])) * 100
  slo.yaml: |-
    spec_version: '1.0'
    comparison:
      compare_with: "single_result"
      include_result_with_score: "pass"
      aggregate_function: avg
    objectives:
      - sli: error_percentage
        pass:
          - criteria:
            - "<10"
        warning:
          - criteria:
            - "<=5"
    total_score:
      pass: "100%"
      warning: "75%"

