apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-bookinfo"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "evaluation"
          tasks:
          - name: "test"
            properties:
              teststrategy: "functional"
          - name: "evaluation"