kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: brigade-crb
  namespace: default
subjects:
- kind: ServiceAccount 
  namespace: default
  name: brigade-worker
roleRef:
  kind: ClusterRole 
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io