apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: brigade-cr
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: brigade-crb
  namespace: default
subjects:
- kind: ServiceAccount 
  namespace: default
  name: brigade-worker
roleRef:
  kind: ClusterRole 
  name: brigade-cr
  apiGroup: rbac.authorization.k8s.io