{{ $pluginsEnabled := false}}
{{ range $plugin := .Values.plugins }}{{ if $plugin.enabled }}{{ $pluginsEnabled = true}}{{ end }}{{ end }}
{{ if not .Values.ci.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orkestra.fullname" . }}
  labels:
    {{- include "orkestra.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "orkestra.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orkestra.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "orkestra.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: 
          - --staging-repo-url
          - http://{{ .Release.Name }}-chartmuseum.{{ .Release.Namespace }}:8080
          - --config
          - /etc/controller/config.yaml
          - --chart-store-path
          - {{ .Values.chartStorePath }} 
          {{- if .Values.remediation.disabled }}
          - --disable-remediation
          {{- end }}
          {{- if .Values.cleanup.enabled }}
          - --cleanup-downloaded-charts
          {{- end }}
          {{ if .Values.debug.enabled }}
          - --debug
          {{- end }}
          {{- if $pluginsEnabled -}}
          - --with-plugins={{ range $index, $plugin := .Values.plugins }}{{ if $plugin.enabled }}{{ if $index }},{{ end }}{{ $plugin.name }}{{end}}{{end}}
          {{- end }}
          env:
          {{- if .Values.keptn.enabled }}
          - name: GITEA_ADMIN_PASSWORD
            value: {{ .Values.gitea.gitea.admin.password }}
          - name: GITEA_URL
            value: {{ .Values.gitea.url }}
          - name: GITEA_USERNAME
            value: {{ .Values.gitea.username }}
          - name: GITEA_PASSWORD
            value: {{ .Values.gitea.password}}
          {{- end }}
          - name: WORKFLOW_NAMESPACE 
            value: {{ .Release.Namespace }} 
          - name: WORKFLOW_SERVICEACCOUNT_NAME 
            value: {{ include "orkestra.serviceAccountName" . }} 
          {{- if .Values.ci.enabled }}
          - name: CI_ENVTEST_CHARTMUSEUM_URL
            value: {{ .Values.ci.env.chartmuseumURL }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # define a liveness probe that checks every 5 seconds, starting after 5 seconds
          livenessProbe:
            httpGet:
              path: /live
              port: 8086
            initialDelaySeconds: 5
            periodSeconds: 5

          # define a readiness probe that checks every 5 seconds
          readinessProbe:
            httpGet:
              path: /ready
              port: 8086
            periodSeconds: 5
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
