kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  {{ include "orkestra.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }} 
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
  
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "orkestra.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }} 
subjects:
- kind: ServiceAccount 
  name: {{ include "orkestra.serviceAccountName" . }} 
  namespace: {{ .Release.Namespace }} 
roleRef:
  kind: ClusterRole 
  name: {{ include "orkestra.serviceAccountName" . }} 
  apiGroup: rbac.authorization.k8s.io