
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - orkestra.azure.microsoft.com
  resources:
  - applicationgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orkestra.azure.microsoft.com
  resources:
  - applicationgroups/status
  verbs:
  - get
  - patch
  - update
