apiVersion: orkestra.azure.microsoft.com/v1alpha1
kind: ApplicationGroup
metadata:
  name: bookinfo 
spec:
  applications:
    - name: bookinfo 
      dependencies: [ambassador]
      spec:
        chart:
          url: "https://nitishm.github.io/charts"
          name: bookinfo 
          version: v1
        release:
          targetNamespace: bookinfo 
          values:
            productpage:
              replicaCount: 1
            details:
              replicaCount: 1
            reviews:
              replicaCount: 1
            ratings:
              replicaCount: 1
        workflow:
          - name: helmrelease
            dependencies: []
            # image: azureorkestra/executor:v0.4.2
            type: helmrelease
            params: nil
          - name: keptn
            dependencies: ["helmrelease"]
            # image: azureorkestra/keptn-executor:v0.1.0
            type: keptn
            params:
              configmapRef: 
                name: keptn-config
                namespace: orkestra
          - name: my-custom-executor
            dependencies: ["helmrelease"]
            image: azureorkestra/my-custom-executor:v0.1.0
            params:
              foo: 
                bar: value
                baz: value


