apiVersion: orkestra.azure.microsoft.com/v1alpha1
kind: ApplicationGroup
metadata:
  name: bookinfo 
spec:
  applications:
    - name: ambassador
      dependencies: []
      spec:
        namespace: orkestra
        repo: datawire 
        groupID: "bookinfo"
        subcharts: []
        chart:
          repository: "https://www.getambassador.io"
          name: ambassador 
          version: 6.6.0
        overlays:
          service:
            type: ClusterIP
        forceUpgrade: true
        targetNamespace: ambassador 
    - name: bookinfo 
      dependencies: [ambassador]
      spec:
        namespace: orkestra 
        repo: bookinfo 
        groupID: "bookinfo"
        subcharts:
        - name: productpage
          dependencies: [reviews]
        - name: reviews
          dependencies: [details, ratings]
        - name: ratings
          dependencies: []
        - name: details
          dependencies: []
        chart:
          repository: "https://nitishm.github.io/istio-bookinfo-chart"
          name: bookinfo 
          version: v1
        overlays:
          productpage:
            replicaCount: 1
          details:
            replicaCount: 1
          reviews:
            replicaCount: 1
          ratings:
            replicaCount: 1
        forceUpgrade: true
        targetNamespace: bookinfo
