apiVersion: orkestra.azure.microsoft.com/v1alpha1
kind: ApplicationGroup
metadata:
  name: dev
spec:
  applications:
    # ERROR: Kafka fails on kind cluster causing the workflow to stall
    # - name: kafka-dev
    #   dependencies:
    #     - redis-dev
    #   spec: 
    #     namespace: "orkestra"
    #     repo: bitnami
    #     groupID: "dev"
    #     subcharts:
    #       # subchart ordering
    #       - name: zookeeper
    #         dependencies: []
    #     # HelmRelease spec fields
    #     # https://docs.fluxcd.io/projects/helm-operator/en/1.0.0-rc9/references/helmrelease-custom-resource.html#helmrelease-custom-resource
    #     chart:
    #       repository: "https://charts.bitnami.com/bitnami"
    #       name: kafka
    #       version: 12.4.1
    #     overlays:
    #       global:
    #         imagePullSecrets: []
    #       zookeerper:
    #         enabled: true
    #     targetNamespace: "kafka-dev-ns"
    #     forceUpgrade: true
    - name: redis-dev
      spec:
        namespace: "orkestra"
        repo: bitnami
        groupID: "dev"
        subcharts: []
        # HelmRelease spec fields
        # https://docs.fluxcd.io/projects/helm-operator/en/1.0.0-rc9/references/helmrelease-custom-resource.html#helmrelease-custom-resource
        chart:
          repository: "https://charts.bitnami.com/bitnami"
          name: redis
          version: 12.2.3
        overlays:
          global:
            imagePullSecrets: []
          master:
            persistence: 
              size: 4Gi
        targetNamespace: "redis-dev-ns"
        forceUpgrade: true

# TODO (nitishm) - define these fields using Argo Workflow spec
#  strategy:
#    rollout:
#    backout: