# namespace: &namespace orkestra
serviceAccount: &serviceAccount orkestra

replicaCount: 1

chartStorePath: "/etc/orkestra/charts/pull"

image:
  repository: azureorkestra/orkestra
  pullPolicy: Always 
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: *serviceAccount

ci:
  enabled: false
  env:
    chartmuseumURL: "http://127.0.0.1:8080"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

remediation:
  disabled: false

# set to dev mode until MVP
cleanup:
  enabled: false

# set to dev mode until MVP
debug:
  enabled: false

logLevel: 5


# Dependency overlay values
chartmuseum:
  name: chartmuseum
  interval: 10s
  env:
    open:
      DISABLE_API: false

argo:
  images:
    pullPolicy: IfNotPresent

  init:
    serviceAccount: *serviceAccount

  workflow:
    # namespace: *namespace
    serviceAccount:
      name: *serviceAccount
    rbac:
      enabled: false

  controller:
    # serviceAccount: *serviceAccount
    name: workflow-controller
    # workflowNamespaces:
      # - *namespace
    containerRuntimeExecutor: k8sapi # Most Secure - https://argoproj.github.io/argo-workflows/workflow-executors/#kubernetes-api-k8sapi

  server:
    enabled: true
    name: argo-server
    serviceAccount: *serviceAccount
    createServiceAccount: false

helm-controller:
  concurrent: 5
  enabled: true
  serviceAccount:
    create: false
    name: *serviceAccount 
  source-controller:
    serviceAccount:
      create: false
      name: *serviceAccount
