namespace: &namespace orkestra
serviceAccount: &serviceAccount orkestra

replicaCount: 1

image:
  repository: azureorkestra/orkestra
  pullPolicy: Always 
  tag: "v0.2.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: *serviceAccount

repositories:
  - name: staging 
    url: "http://orkestra-chartmuseum.orkestra:8080"
  - name: bitnami
    url: "https://charts.bitnami.com/bitnami"
    # username: admin
    # password: password
    # authHeader: 'Authorization: Basic HTTPBASICAUTHCREDS'
    # caFile: /path/to/ca/file
    # certFile: /path/to/cert/file
    # keyFile: /path/to/key/file
    # insecureSkipVerify: false

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# Dependency overlay values
chartmuseum:
  env:
    open:
      DISABLE_API: false 

helm-operator:
  rbac:
    create: false 
    pspEnabled: false 
  serviceAccount:
    create: false 
    annotations: {}
    name: *serviceAccount
  helm:
    versions: "v3"

argo:
  images:
    pullPolicy: IfNotPresent

  init:
    serviceAccount: *serviceAccount

  workflow:
    namespace: *namespace
    serviceAccount:
      name: *serviceAccount
    rbac:
      enabled: false

  controller:
    # serviceAccount: *serviceAccount
    name: workflow-controller
    workflowNamespaces:
      - *namespace
    containerRuntimeExecutor: docker
    # For KinD use -
    # containerRuntimeExecutor: k8sapi

  server:
    enabled: true
    name: argo-server
    serviceAccount: *serviceAccount
    createServiceAccount: false
