registries:
  primary:
    url: "https://primary-repo.acme.com/"
    username: "admin"
    password: "password"
    accessToken: "eyJpc3MiOiJodHRwczovL2V4YW1wbGUuYXV0aDAuY29tLyIsImF1ZCI6Imh0dHBzOi8vYXBpLmV4YW1wbGUuY29tL2NhbGFuZGFyL3YxLyIsInN1YiI6InVzcl8xMjMiLCJpYXQiOjE0NTg3ODU3OTYsImV4cCI6MTQ1ODg3MjE5Nn0"
    authHeader: "alternateAuthTokenHeader"
    caFile: "/path/to/ca/cert"
    certFile: "/path/to/certfile"
    keyFile: "path/to/keyfile"
    insecureSkipVerify: true

  bitnami:
    url: "https://charts.bitnami.com/bitnami"
    insecureSkipVerify: true

  staging:
    url: "http://localhost:8080"
    # Uncomment this when deployed in cluster
    # url: "http://my-chartmuseum-chartmuseum.default:8080"