name: API Docs
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: gen-crd-api-reference-docs
        run: make api-docs
      - name: Check if docs are up to date
        # This check must fail if there are diffs.
        run: git diff --exit-code ./docs/api.md
